export const CHANGE_LANGUAGE = "HEADER/CHANGE_LANGUAGE";
export const CHANGE_MAINTEXT = "HEADER/CHANGE_MAINTEXT";

//! PANELOFCARDS TYPES
export const CREATE_CARD = "PANELOFCARDS/CREATE_CARD";
export const UPDATE_CARD = "PANELOFCARDS/UPDATE_CARD";
export const DELETE_CARD = "PANELOFCARDS/DELETE_CARD";
export const FETCH_CARDS = "PANELOFCARDS/FETCH_CARDS";

export const SET_FAMILY_CARDS = "PANELOFCARDS/SET_FAMILY_CARDS";
export const SET_FUN_CARDS = "PANELOFCARDS/SET_FUN_CARDS";
//!For drag'n'drop
// export const UPDATE_FAMILY_CARDS = "PANELOFCARDS/UPDATE_FAMILY_CARDS";
// export const UPDATE_FUN_CARDS = "PANELOFCARDS/UPDATE_FUN_CARDS";

export const ENABLE_EDIT_CARD = "CARD/ENABLE_EDIT_CARD";
export const DISABLE_EDIT_CARD = "CARD/DISABLE_EDIT_CARD";
//! PANELOFCARDS TYPES END

//! APP TYPES
export const SHOW_LOADER = "APP/SHOW_LOADER";
export const HIDE_LOADER = "APP/HIDE_LOADER";
export const SHOW_ALERT = "APP/SHOW_ALERT";
export const HIDE_ALERT = "APP/HIDE_ALERT";
export const FETCH_PRESETS = "APP/FETCH_PRESETS";
//! APP TYPES END

//! NOTICEPANEL TYPES
export const FETCH_SENDER_NOTIFICATIONS =
  "NOTICEPANEL/FETCH_SENDER_NOTIFICATIONS";
//!
